# Generated by Django 4.2.5 on 2024-01-18 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('streamers', '0003_person'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='contacts',
            field=models.ManyToManyField(blank=True, to='streamers.profile'),
        ),
        migrations.AddField(
            model_name='profile',
            name='notifications',
            field=models.TextField(blank=True, default=''),
        ),
    ]
