# Generated by Django 4.2.5 on 2024-01-13 05:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('streamers', '0003_person'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='birthdate',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
