# Generated by Django 4.2.6 on 2024-02-01 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stream', '0002_alter_vidstream_id_vidrequest_userinfo_setting_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='permission',
            field=models.IntegerField(choices=[(1, 'Patient'), (2, 'Doctor'), (3, 'Admin')], default=1),
        ),
    ]
