# Generated by Django 4.2.5 on 2024-03-24 00:15

from django.db import migrations, models
import stream.storage_backends


class Migration(migrations.Migration):

    dependencies = [
        ('stream', '0002_friendrequest_remove_vidstream_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='video',
            field=models.FileField(storage=stream.storage_backends.MediaStorage(), upload_to=''),
        ),
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='mountain.jpg', storage=stream.storage_backends.ProfilePictureStorage(), upload_to=''),
        ),
    ]
