# Generated by Django 4.2.6 on 2024-03-12 20:39

from django.db import migrations
import s3direct.fields


class Migration(migrations.Migration):

    dependencies = [
        ('stream', '0002_friendrequest_remove_vidstream_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vidstream',
            name='video',
            field=s3direct.fields.S3DirectField(blank=True),
        ),
    ]
