# Generated by Django 4.2.6 on 2024-02-03 23:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stream', '0002_alter_vidstream_id_vidrequest_userinfo_setting_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='friendRequest_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='stream.friendrequest'),
        ),
        migrations.AddField(
            model_name='notification',
            name='post_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='stream.post'),
        ),
        migrations.AddField(
            model_name='notification',
            name='type',
            field=models.IntegerField(choices=[(1, 'Friend Request Send'), (2, 'Accept/Reject Friend Request'), (3, 'Video Request Send'), (4, 'Video Request Receive'), (5, 'Post Upload'), (6, 'Video Upload')], null=True),
        ),
        migrations.AddField(
            model_name='notification',
            name='videoRequest_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='stream.vidrequest'),
        ),
        migrations.AddField(
            model_name='notification',
            name='video_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='stream.vidstream'),
        ),
        migrations.AddField(
            model_name='userinfo',
            name='permission',
            field=models.IntegerField(choices=[(1, 'Patient'), (2, 'Doctor'), (3, 'Admin')], default=1),
        ),
    ]
