# Generated by Django 4.2.5 on 2024-03-24 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stream', '0003_alter_post_video_alter_profile_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vidstream',
            name='description',
        ),
        migrations.RemoveField(
            model_name='vidstream',
            name='title',
        ),
        migrations.AlterField(
            model_name='vidstream',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
