# Generated by Django 4.2.5 on 2024-02-10 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stream', '0003_notification_friendrequest_id_notification_post_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
