# Generated by Django 4.2.6 on 2024-02-10 23:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stream', '0003_notification_friendrequest_id_notification_post_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='friendRequest_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='stream.friendrequest'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.IntegerField(choices=[(1, 'Friend Request Send'), (2, 'Accept/Reject Friend Request'), (3, 'Video Request Send'), (4, 'Video Request Receive'), (5, 'Post Upload'), (6, 'Video Upload'), (7, 'Text')], null=True),
        ),
    ]
