# Generated by Django 4.2.5 on 2024-01-26 07:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stream', '0003_alter_notification_id_friendrequset_contact'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='request_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='stream.vidrequest'),
        ),
        migrations.AlterField(
            model_name='post',
            name='video_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='stream.vidstream'),
        ),
    ]
