# Generated by Django 4.2.5 on 2024-01-24 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stream', '0003_userinfo_setting_profile_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='contacts',
            field=models.ManyToManyField(blank=True, to='stream.profile'),
        ),
        migrations.AddField(
            model_name='profile',
            name='notifications',
            field=models.TextField(blank=True, default=' '),
        ),
    ]
