# Generated by Django 5.0.2 on 2024-02-24 04:00

import s3direct.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stream', '0004_alter_notification_friendrequest_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='permission',
            field=models.IntegerField(choices=[(1, 'Sender'), (2, 'Receiver'), (3, 'Admin')], default=1),
        ),
        migrations.AlterField(
            model_name='vidstream',
            name='video',
            field=s3direct.fields.S3DirectField(blank=True),
        ),
    ]
