# Generated by Django 4.2.5 on 2024-03-29 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stream', '0004_remove_vidstream_description_remove_vidstream_title_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='video',
            field=models.URLField(),
        ),
    ]
