# Generated by Django 4.2.5 on 2024-03-24 08:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stream', '0004_remove_vidstream_description_remove_vidstream_title_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='video',
        ),
    ]
