# Generated by Django 4.2.5 on 2024-03-29 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stream', '0004_remove_vidstream_description_remove_vidstream_title_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='security_answer',
            field=models.CharField(default=' ', max_length=300),
        ),
        migrations.AddField(
            model_name='userinfo',
            name='security_question',
            field=models.IntegerField(choices=[(1, 'What was the name of your first pet?'), (2, 'In which city were you born?'), (3, 'What is the middle name of your oldest sibling?'), (4, 'What is the name of your favorite sports team?'), (5, 'What was the make and model of your first car?')], default=1),
        ),
    ]
