# Generated by Django 4.2.5 on 2024-01-28 07:19

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('stream', '0004_alter_post_request_id_alter_post_video_id'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='FriendRequset',
            new_name='FriendRequest',
        ),
    ]
