# Generated by Django 4.2.5 on 2024-02-24 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("stream", "0004_alter_notification_friendrequest_id_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userinfo",
            name="permission",
            field=models.IntegerField(
                choices=[(1, "Sender"), (2, "Receiver"), (3, "Admin")], default=1
            ),
        ),
    ]
