# Generated by Django 4.2.5 on 2024-02-21 03:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('stream', '0004_alter_notification_friendrequest_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='permission',
            field=models.IntegerField(choices=[(1, 'Sender'), (2, 'Receiver'), (3, 'Admin')], default=1),
        ),
        migrations.AlterField(
            model_name='vidrequest',
            name='receiver',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='video_receiver', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='vidrequest',
            name='sender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='video_sender', to=settings.AUTH_USER_MODEL),
        ),
    ]
