# Generated by Django 4.2.5 on 2024-01-26 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stream', '0004_alter_post_request_id_alter_post_video_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='contacts',
            field=models.ManyToManyField(blank=True, to='stream.profile'),
        ),
        migrations.AddField(
            model_name='profile',
            name='notifications',
            field=models.TextField(blank=True, default=''),
        ),
    ]
