# Generated by Django 4.2.5 on 2024-02-22 01:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stream', '0005_alter_userinfo_permission_alter_vidrequest_receiver_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='videoRequest_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='stream.vidrequest'),
        ),
    ]
