# Generated by Django 5.0.2 on 2024-02-25 00:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stream', '0005_alter_userinfo_permission_alter_vidstream_video'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vidstream',
            name='video',
            field=models.FileField(upload_to=''),
        ),
    ]
