# Generated by Django 4.2.5 on 2024-03-30 00:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stream', '0005_userinfo_security_answer_userinfo_security_question'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='is_read',
            field=models.BooleanField(default=False),
        ),
    ]
