# Generated by Django 4.2.5 on 2024-03-24 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stream', '0005_remove_post_video'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='video',
            field=models.URLField(null=True),
        ),
    ]
