# Generated by Django 4.2.5 on 2024-03-01 19:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stream', '0006_alter_notification_videorequest_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vidstream',
            name='description',
        ),
        migrations.RemoveField(
            model_name='vidstream',
            name='title',
        ),
    ]
