# Generated by Django 4.2.5 on 2024-03-09 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stream', '0007_remove_vidstream_description_remove_vidstream_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.IntegerField(choices=[(1, 'Friend Request Send'), (2, 'Accept/Reject Friend Request'), (3, 'Video Request Send'), (4, 'Video Request Receive'), (5, 'Post Upload'), (6, 'Post Receive'), (7, 'Video Upload'), (8, 'Text')], null=True),
        ),
    ]
