"""
Django settings for video_app project.

Generated by 'django-admin startproject' using Django 2.2.18.

For more information on this file, see
https://docs.djangoproject.com/en/2.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/2.2/ref/settings/
"""
from pathlib import Path
import os
from pathlib import Path

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
# BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
BASE_DIR = Path(__file__).resolve().parent.parent

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/2.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'fpfd*qb+!is4hf@l6c(0n*1v4syzidbwzfsm-^%c30x*&772wc'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ["*"]
# ALLOWED_HOSTS = ['ebdjango-env-1.eba-uzn2yvai.ca-central-1.elasticbeanstalk.com']

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'stream.apps.StreamConfig',
    # 'streamers.apps.StreamersConfig',
    'bootstrap5',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
]

ROOT_URLCONF = 'video_app.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'video_app.wsgi.application'


# Database
# https://docs.djangoproject.com/en/2.2/ref/settings/#databases

# Local SQLite3 database
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': os.path.join(BASE_DIR, 'db.sqlite3'),
    }
}

# AWS RDS database
# DATABASES = {
#   'default': {
#     'ENGINE': 'django.db.backends.postgresql_psycopg2',
#     'NAME': 'djangodatabase',
#     'USER': 'masteruser',
#     'PASSWORD': 'masteruser',
#     'HOST': 'database-django.cqtxhhmhjnhu.ca-central-1.rds.amazonaws.com',
#     'PORT': '5432',
#   }
# }


# Password validation
# https://docs.djangoproject.com/en/2.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/2.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'America/Los_Angeles'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/2.2/howto/static-files/

STATIC_ROOT = BASE_DIR / 'productionfiles'

STATIC_URL = 'static/'

#Add this in your settings.py file:
STATICFILES_DIRS = [
    BASE_DIR / 'static'
]

LOGIN_REDIRECT_URL = '/'
LOGIN_URL = 'login'

AWS_ACCESS_KEY_ID="ASIA4HU6ILMRBBIIMS4K"
AWS_SECRET_ACCESS_KEY="13oZHDSBVVL9/SF+oBXWkG6WIpYWxrD1W17J6jmJ"
AWS_SESSION_TOKEN="IQoJb3JpZ2luX2VjEE4aDGNhLWNlbnRyYWwtMSJGMEQCIEeHDDpBTn+caSvguq4vtnPC+wIjHiLdMsnicMXhRtXnAiAFrmh1dnE8NpIncRQTEb5QbH4LizcDQy2eDiK4jTy+EyqOAwhnEAAaDDg0MTA3MTc0NTgyNiIMaaFaJmQ66sWdpKOhKusCfDmgNVUSU/Gl+yMVleCt3J5vHaQBG9KfIMuD8iLLOT4SyOFH4TkDY1fA8X5ZYS1fqvWgnP0uy8UfavBRKjoJMZLI9QVb+9rJauqqZBe/i42lodXBHGbcSyBgz7uasgBX8CUqV2xSPyJNzaOtsIoDwhMmHDdr+OsD3D56xs1YVraLbC1HWqCkR0TWi4ItORH8Iu5JMK4X0F5yh8NfU+HakLuXtxSWRGdQ0CpmcxI8JMeOYxWEJ8PXwcUfAS5MRdw0ABDj1ipFG36/4UwllEVx6rVqPAi3yubfOVzO/r+mIaLQGw2LWsJ8UJqAq8iodfmiFVGuBRzqPMmLxOQSvJMKACrYSCPmTqAE/U0ia6UGThWHjqGlDbbhlZUVQYgGu0DJX06Pz/kgnwo9z5Am1u+nn2IQdkLOo2uxIQWAARvYdJJ4e+Pzgyri8woVmIy7CyiKLba8qsAyRANS6y4aW/1p1Kksj+14WDwE+mSZMMOa/a8GOqcB2FWTJzFOZI4WEgpFFfdK4U8tw6ltEcX/iMooLBWyBWvASp645UO7moNpwrPF3KQONH3E9rXfIfLX2lQGKjABZG4YbmHi53PDX1mj7pIwQ9ekDE876aTg/kekTtItHSmFtGJUFyDYipEjMdhQ0MCQlVVDmw89vK1Ya3I7vwBHNFjLo0WKTqmlTHX7/TQnvLYjnozfSd20Ctm7M2BTYsIIXnUBWB+M8fg="

AWS_STORAGE_BUCKET_NAME = 'elasticbeanstalk-ca-central-1-841071745826'
AWS_S3_CUSTOM_DOMAIN = f'{AWS_STORAGE_BUCKET_NAME}.s3.amazonaws.com'
AWS_S3_REGION_NAME = "ca-central-1"
AWS_S3_SIGNATURE_VERSION = "s3v4"
AWS_QUERYSTRING_EXPIRE = 604800
CLOUDFRONT_DOMAIN = 'd18u3jaflgrcvn.cloudfront.net'
AWS_CLOUDFRONT_DOMAIN = 'd18u3jaflgrcvn.cloudfront.net'
AWS_S3_REGION_NAME = 'ca-central-1'
AWS_S3_ENDPOINT_URL = f'https://s3.{AWS_S3_REGION_NAME}.amazonaws.com'

S3DIRECT_DESTINATIONS = {
    'primary_destination': {
        'key': 'uploads/',
        'allowed': ['image/jpg', 'image/jpeg', 'image/png', 'video/mp4'],
    },
}


# MEDIA_ROOT = os.path.join(BASE_DIR, 'media')
# MEDIA_URL = '/media/'

MEDIAFILES_LOCATION = 'media'
MEDIA_URL = f'{CLOUDFRONT_DOMAIN}/media/'

PROFILE_PICTURE_FILES_LOCATION = 'media/profile-pics'
DEFAULT_FILE_STORAGE = 'storages.backends.s3boto3.S3Boto3Storage'

#solves vidstream auto-created primary key error
DEFAULT_AUTO_FIELD='django.db.models.AutoField'

DATA_UPLOAD_MAX_MEMORY_SIZE = 1024 * 1024 * 50  # X is the size in megabytes - 50mb (1 min record video = 5.5mb)
FILE_UPLOAD_MAX_MEMORY_SIZE = 1024 * 1024 * 50  # X is the size in megabytes - 50mb

STATIC_ROOT=os.path.join(BASE_DIR,'productionfiles')
# MEDIA_ROOT=os.path.join(BASE_DIR,'static/media/')
