"""
Django settings for video_app project.

Generated by 'django-admin startproject' using Django 2.2.18.

For more information on this file, see
https://docs.djangoproject.com/en/2.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/2.2/ref/settings/
"""
from pathlib import Path
import os
from pathlib import Path

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
# BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
BASE_DIR = Path(__file__).resolve().parent.parent

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/2.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'fpfd*qb+!is4hf@l6c(0n*1v4syzidbwzfsm-^%c30x*&772wc'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ["*"]
# ALLOWED_HOSTS = ['ebdjango-env-1.eba-uzn2yvai.ca-central-1.elasticbeanstalk.com']

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'stream.apps.StreamConfig',
    # 'streamers.apps.StreamersConfig',
    'bootstrap5',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
]

ROOT_URLCONF = 'video_app.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'video_app.wsgi.application'


# Database
# https://docs.djangoproject.com/en/2.2/ref/settings/#databases

# Local SQLite3 database
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': os.path.join(BASE_DIR, 'db.sqlite3'),
    }
}

# AWS RDS database
# DATABASES = {
#   'default': {
#     'ENGINE': 'django.db.backends.postgresql_psycopg2',
#     'NAME': 'djangodatabase',
#     'USER': 'masteruser',
#     'PASSWORD': 'masteruser',
#     'HOST': 'database-django.cqtxhhmhjnhu.ca-central-1.rds.amazonaws.com',
#     'PORT': '5432',
#   }
# }


# Password validation
# https://docs.djangoproject.com/en/2.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/2.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'America/Los_Angeles'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/2.2/howto/static-files/

STATIC_ROOT = BASE_DIR / 'productionfiles'

STATIC_URL = 'static/'

#Add this in your settings.py file:
STATICFILES_DIRS = [
    BASE_DIR / 'static'
]

LOGIN_REDIRECT_URL = '/'
LOGIN_URL = 'login'

AWS_ACCESS_KEY_ID="ASIA4HU6ILMRFN4OL4GW"
AWS_SECRET_ACCESS_KEY="Qv03eMMg1muKCNNm0wqDaIfVHCacWt3SkrSg/3D2"
AWS_SESSION_TOKEN="IQoJb3JpZ2luX2VjEOD//////////wEaDGNhLWNlbnRyYWwtMSJGMEQCIEg7O15zfslhq4E97wE4vsFSUje6akodBDOKyrJSCj6nAiAw1FjKtxAH4wyG8v/0c66nLI4x/JhzzwA2nMnqze7aMyqZAwj5//////////8BEAAaDDg0MTA3MTc0NTgyNiIMkb8fcZMSfRrThJv/Ku0Cra5ul51H/9aCmHj7w3kgZ5xfUj1RGwbAONx4ezn/TWxpC91b6cr0z330AvbZ+FKb4Oqp+1KYXI4YCbTmKl2g+4CiN6A5W0I9G4l+JRUPggA03jyPXBr4gBArXgwaxAnXWgobG/eSncQPJn/ZG9d/gwKTzJ5SUiwTqpcctB7Nz+mX1oI8W8HNv+ZQ7yxEB7V1unW4mR26wor1ezZ5Zy+Hxwm7Y5I/VZnqjimKSmKy/Fubo6Pq3VSBuORF+qHCkCpm4/wVCCswCdCuUUNO8RvHXEDmEWKWSKY8NcJuG57KtuUvddRq54ijEz3M3d5KloT5VTYE1VlEG7ObW5nTPnLKqx2d6p4i37fjiU0q2HsgCseF6Wa2MwFE0fPeCt5Dkk5jhB+W7WuzedZ5fovDYEhCkoaPgnWBZjC7U+jzpbfbidTL3I65W3/7MD/kz9l2lr4oultRnYq3OxtRLo5z9vuepBV4GdE8ZMcVoyCCwNowtbSdsAY6pwHQ9pF3R/cs18Wu0+Egr5JWlNxDXa31BEVy2kx6eJ1xFKxLjXAuS+LNbWDW+4mk6VETdspTmUlKACRJY9Wq53WKhnhvy0oynEMW0SLAEVyKaZ/KkNmRCRXwRqQ/oW3LmIrmbpi7QZu+xEgMtV++beqiySymnFjUFPrkfusT87/M4KhqIBkR0sCOvqnB/VJElZwaKluCvrGCGL0Goa8znFyTWRRvlyeXiA=="

AWS_STORAGE_BUCKET_NAME = 'elasticbeanstalk-ca-central-1-841071745826'
AWS_S3_CUSTOM_DOMAIN = f'{AWS_STORAGE_BUCKET_NAME}.s3.amazonaws.com'
AWS_S3_REGION_NAME = "ca-central-1"
AWS_S3_SIGNATURE_VERSION = "s3v4"
AWS_QUERYSTRING_EXPIRE = 604800
CLOUDFRONT_DOMAIN = 'd18u3jaflgrcvn.cloudfront.net'
AWS_CLOUDFRONT_DOMAIN = 'd18u3jaflgrcvn.cloudfront.net'
AWS_S3_REGION_NAME = 'ca-central-1'
AWS_S3_ENDPOINT_URL = f'https://s3.{AWS_S3_REGION_NAME}.amazonaws.com'

S3DIRECT_DESTINATIONS = {
    'primary_destination': {
        'key': 'uploads/',
        'allowed': ['image/jpg', 'image/jpeg', 'image/png', 'video/mp4'],
    },
}

# Local media store path
# MEDIA_ROOT = os.path.join(BASE_DIR, 'media')
# MEDIA_URL = '/media/'

# S3 media/profile picture store path
MEDIAFILES_LOCATION = 'media'
MEDIA_URL = f'{CLOUDFRONT_DOMAIN}/media/'

PROFILE_PICTURE_FILES_LOCATION = 'media/profile-pics'
DEFAULT_FILE_STORAGE = 'storages.backends.s3boto3.S3Boto3Storage'

#solves vidstream auto-created primary key error
DEFAULT_AUTO_FIELD='django.db.models.AutoField'

DATA_UPLOAD_MAX_MEMORY_SIZE = 1024 * 1024 * 50  # X is the size in megabytes - 50mb (1 min record video = 5.5mb)
FILE_UPLOAD_MAX_MEMORY_SIZE = 1024 * 1024 * 50  # X is the size in megabytes - 50mb

STATIC_ROOT=os.path.join(BASE_DIR,'productionfiles')
# MEDIA_ROOT=os.path.join(BASE_DIR,'static/media/')   # Media root for local
